// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xrvncxkgntmghoavsuxp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inhydm5jeGtnbnRtZ2hvYXZzdXhwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg2MTMwMTEsImV4cCI6MjA2NDE4OTAxMX0.uqbEV1_Ks8vsAtCOKAx4linyPCprazbtRXWbV4u3qEY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);